const songs = [
  "Tokyo Kick-Ass",
  "Tori no Uta",
  "Sakura",
  "Ride on Time",
  "Plastic Love",
  "Yofukashi no Uta",
  "Bling-Bang-Bang-Born",
  "God Shattering Star",
  "Bibideba",
  "Raktober",
  "Unlucky",
  "Lost in Paradise",
  "Cotton Candy Ei-Ei-Oh",
  "Shinda!",
  "Swinging!",
  "Itsudatte for you!",
  "Rune ga Pikatto Hikattara",
  "Song of the Dead",
  "Watashi Ronri",
  "Love Dramatic",
  "DADDY! DADDY! DO!",
  "Giri Giri",
  "You Spin Me Round",
  "Super Ultra Hyper Miracle Romantic",
  "summertime",
  "Mayonaka No Door",
  "Plastic Love",
  "Aishitageru",
  "Aoi Koufuku",
  "Aquaterrarium",
  "Itsumademo Hibiku kono Melody",
  "Koi wa Illusion",
  "Shokuchuu Shokubutsu",
  "Seiza ni Naretara",
  "Sou Yuu Koto Aru Yo Ne?",
  "KU-RU-KU-RU Cruller!",
  "Shikairo Days",
  "Fly-day Chinatown",
  "Kyuusei Άργυρóϛ",
  "Koakuma Love",
  "Never Say Goodbye",
  "Machi no Dolphin",
  "Watashi no Symphony",
  "Sugar Sugar Yummy Yummy Parfait",
  "Holiday∞Holiday",
  "Ginga Tetsudou no Yoru ni",
  "Kamisama, Hotoke-sama",
  "Dark Crow",
  "Above Your Hand",
  "Uma to Shika",
  "Lady Crazy",
  "Shitsurei Shimasu ga, RIP",
  "Suion no Uta",
  "mo・o!",
  "WE WILL!"
]

export default songs
